SH_company_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('equipments/', include('equipments.urls')),
    path('constructions/', include('constructions.urls')),
    path('performances/', include('performances.urls')),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companies/urls.py
from django.urls import path
from . import views

app_name = 'companies'

urlpatterns = [
    path('', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('history/', views.history, name='history'),
    path('patent/', views.patent, name='patent'),
    path('come/', views.come, name='come'),
]

notices/urls.py
from django.urls import path
from . import views

app_name = 'notices'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # create라는 주소로 요청하면, create라는 VIEW 함수를 응답
    path('<int:notice_pk>/', views.detail, name='detail'),
    path('<int:notice_pk>/update/', views.update, name='update'),
    path('<int:notice_pk>/delete', views.delete, name='delete'),
    path('search/', views.search, name='search')
]

companies/models.py
from django.db import models

# Create your models here.

companies/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'companies/index.html')

def greeting(request):
    return render(request, 'companies/greeting.html')
    
def history(request):
    return render(request, 'companies/history.html')

def patent(request):
    return render(request, 'companies/patent.html')

def come(request):
    return render(request, 'companies/come.html')

companies/templates/companies/come.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

{% endblock %}

{% block content %}

<div style="margin-top: 100px;" class="card text-bg-dark">
    <img style="height: 150px; filter: brightness(50%); background-size: cover; object-fit: cover;" 
         src="{%static 'images/60.png'%}" class="card-img" alt="회사소개 윗부분 사진입니다.">
    <div class="card-img-overlay">
        <div style="margin-top: 50px; margin-left: 90px;">
            <p style="text-align: center; animation: fadeIn; animation-duration: 2s; font-size: 27px;" 
               class="animate__animated animate__fadeIn card-title">
               SH건설산업 기계타설전문 홈페이지를방문해주신 여러분 진심으로 환영합니다.
            </p>
        </div>
  </div>


  <div style="background-color: #fff;" class="content">
    <div class="container text-center">
      <div class="row">
        <div class="col-sm-4">
          <div style="margin-top: 100px;">
              <ul style="  margin-left: 80px; text-align: left;">
                  <li style=" margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:greeting' %}">
                      회사소개
                    </a>
                  </li>
                  <li style=" margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:history' %}">회사연혁</a>
                  </li>
                  <li style="font-weight: 700; margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:patent' %}">특허및인증</a>
                  </li>
                  <li style="font-weight: 700; margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:come' %}">오시는길</a>
                  </li>
              </ul>
          </div>
        </div>
  
        <!-- 세로선 -->
  
    
        <div style="margin-bottom: 300px; color: #000; margin-top: 100px; height: 500px;" class="col-sm-8">
          <div>
            <div id="map" style="width:50rem;height:21rem;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>




<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=202d51da97fdb12f363699e01a90c11f&libraries=services"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = {
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };  

// 지도를 생성합니다    
var map = new kakao.maps.Map(mapContainer, mapOption); 

// 주소-좌표 변환 객체를 생성합니다
var geocoder = new kakao.maps.services.Geocoder();

// 주소로 좌표를 검색합니다
geocoder.addressSearch('경기도 안성시 미양면 양변길 159', function(result, status) {

    // 정상적으로 검색이 완료됐으면 
     if (status === kakao.maps.services.Status.OK) {

        var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

        // 결과값으로 받은 위치를 마커로 표시합니다
        var marker = new kakao.maps.Marker({
            map: map,
            position: coords
        });

        // 인포윈도우로 장소에 대한 설명을 표시합니다
        var infowindow = new kakao.maps.InfoWindow({
            content: '<div class="fw-bold" style="color:black;width:9rem;text-align:center;padding:0.3rem 0;">SH건설산업(주)</div>'
        });
        infowindow.open(map, marker);

        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
    } 
});    
</script>


{% endblock %}

companies/templates/companies/greeting.html
{% extends 'base.html' %}
{% load static %}

{% block css %}


{% endblock css %}

{% block content %}

<!-- banner 생성구간입니다. -->
<div style="margin-top: 100px;" class="card text-bg-dark">
  <img style="height: 150px; filter: brightness(50%); background-size: cover; object-fit: cover;" 
       src="{%static 'images/60.png'%}" class="card-img" alt="회사소개 윗부분 사진입니다.">
  <div class="card-img-overlay">
      <div style="margin-top: 50px; margin-left: 90px;">
          <p style="text-align: center; animation: fadeIn; animation-duration: 2s; font-size: 27px;" 
             class="animate__animated animate__fadeIn card-title">
             SH건설산업 기계타설전문 홈페이지를방문해주신 여러분 진심으로 환영합니다.
          </p>
      </div>
</div>

<!--  -->
<div style="background-color: #fff;" class="content">
  <div class="container text-center">
    <div class="row">
      <div class="col-sm-4">
        <div style="margin-top: 100px;">
            <ul style="  margin-left: 80px; text-align: left;">
                <li style=" margin-bottom: 30px;">
                  <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:greeting' %}">
                    회사소개
                  </a>
                </li>
                <li style=" margin-bottom: 30px;">
                  <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:history' %}">회사연혁</a>
                </li>
                <li style="font-weight: 700; margin-bottom: 30px;">
                  <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:patent' %}">특허및인증</a>
                </li>
                <li style="font-weight: 700; margin-bottom: 30px;">
                  <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:come' %}">오시는길</a>
                </li>
            </ul>
        </div>
      </div>

      <!-- 세로선 -->

  
      <div style="margin-bottom: 300px; color: #000; margin-top: 100px; height: 500px;" class="col-sm-8">
        <div style="margin-left: 90px;">
          <div class="row">
            <div style="padding: 0px; width: 20px;" class="col">
              <div style="width: 14px; height: 50px; background-color: #14402B;"></div>
            </div>
            <div class="col">
              <span style="display: inline; width: 70px; margin-top: 0px; font-weight: 700;" class="text-center">“끊임없는 기술혁신을 통하여 최상의 시공품질 유지" <br>
                <!-- “안녕하세요! 에스에이치건설산업 주식회사를 찾아주셔서 감사합니다.”  -->
              </span>
            </div>
            <div style="margin-left: 180px; padding: 0px; width: 20px;" class="col">
              <div style=" width: 14px; height: 50px; background-color: #14402B;"></div>
            </div>
          </div>
        </div>

        <br><br>
        <div style="padding-right: 110px; padding-left: 20px;">
          <div style="border-radius: 30px;" class="card">
            <div style="border-radius: 30px; color: #fff; background-color: #14402B;" class="card-body">
              <p>
                에스에이치건설산업 주식회사는 정직과 신뢰를 우선으로 하는 경영이념 아래  <br> 열정과 도전정신을
                회사의 최고의 목표로 하고 있으며, 지금까지의 경험과 시공노하우를 <br>
                우수한 인력을 통해 최상의 시공품질을 만들어 왔습니다.<br><br>
                에스에이치건설산업 주식회사는 L형측구, 배수공, 터널공동구, 중앙분리대, 철도터널공동구, <br>도로경계석,  교량난간 방호벽 등 콘크리트기계화시공 전문업체입니다. <br>
                믿음과 신뢰를 중요시하는 에스에이치건설산업 주식회사는 <br> 끊임없는 연구와 기술개발을 통하여 콘크리트기계화시공 및 철도 토목분야에 이르기까지 <br> TOTAL 종합시공 시스템을 보유하고 있습니다. <br><br>
      
                당사는 다년간의 경험과 노하우를 바탕으로 콘크리트 기계화 시공은 물론 각종 철도관련 시공에 이르기까지 대한민국 건설의 모든 현장에 함께하고 있습니다. <br> 에스에이치건설산업 주식회사는 설립 이래 끊임없는 변화와 혁신으로 업계를 주도하며 이제는 콘크리트 기계화 시공분야에서 최고의 기업으로 자리매김 하였습니다. <br><br>
      
                에스에이치건설산업 주식회사는 선두의 자리는 차지하는 것 보다는 지키는 것이 <br> 더 어렵다는 것을 누구보다도 잘 알고 있습니다. <br> 
                현재의 위치에 안주하지 않고, 축적된 기술력과 우수한 인력을 바탕으로 <br> 다시 한번 도약을 준비하고 있습니다. <br><br> 
                그 누구보다 고객을 먼저 생각하는 사랑받는 기업이 되겠습니다.<br>
      
                앞으로 당사 모든 임직원 일동은 제품에 대한 최고의 품질과 서비스로<br> 고객만족에 앞장설 것이며,  고객의 고마움에 보답할 것을 약속드립니다. <br><br> 감사합니다.
            </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

companies/templates/companies/history.html
{% extends 'base.html' %}
{% load static %}

{% block css %}


{% endblock css %}

{% block content %}

<!-- banner 생성구간입니다. -->
<div style="margin-top: 100px;" class="card text-bg-dark">
  <img style="height: 150px; filter: brightness(50%); background-size: cover; object-fit: cover;" 
       src="{%static 'images/60.png'%}" class="card-img" alt="회사소개 윗부분 사진입니다.">
  <div class="card-img-overlay">
      <div style="margin-top: 50px; margin-left: 90px;">
          <p style="text-align: center; animation: fadeIn; animation-duration: 2s; font-size: 27px;" 
             class="animate__animated animate__fadeIn card-title">
             SH건설산업 기계타설전문 홈페이지를방문해주신 여러분 진심으로 환영합니다.
          </p>
      </div>
</div>

<!--  -->
<div style="background-color: #fff;" class="content">
  <div class="container text-center">
    <div class="row">
      <div class="col-sm-4">
        <div style="margin-top: 100px;">
            <ul style=" list-style: none; margin-left: 50px; text-align: left;">
              <li style=" margin-bottom: 30px;">
                <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:greeting' %}">
                  회사소개
                </a>
              </li>
              <li style=" margin-bottom: 30px;">
                <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:history' %}">회사연혁</a>
              </li>
              <li style="font-weight: 700; margin-bottom: 30px;">
                <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:patent' %}">특허및인증</a>
              </li>
              <li style="font-weight: 700; margin-bottom: 30px;">
                <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:come' %}">오시는길</a>
              </li>
            </ul>
        </div>
      </div>

      <!-- 세로선 -->

      <!-- 2020 -->
        <div style=" margin-bottom: 400px; color: #000; margin-top: 100px; height: 500px;" class="col-sm-8">
          <div style="left: 790px; width: 175px; height: 161px; position: absolute; background-color: #9AAEA7; border-radius: 50%;">
            <p style="margin-top: 30px; left: 45px; position: absolute; text-align: center; font-weight: 700; font-size: 36px;">2020</p>
            <div style="margin-top: 95px; left: 67px; position: absolute; width: 37px; height: 35px; background-color: #14402B; border-radius: 50%;"></div>
            <p style="position: absolute; width: 339px; font-weight: 700; line-height: 30px; left: 160px; margin-top: 60px;">에스에이치 건설산업(주) 설립</p>
            <div style="position: absolute; border: 3px solid #14402B; width: 432px; height: 0px; margin-top: 110px; left: 70px;"></div>
          </div>

          <div style="margin-top: 200px; left: 790px; width: 175px; height: 161px; position: absolute; background-color: #9AAEA7; border-radius: 50%;">
            <p style="margin-top: 30px; left: 45px; position: absolute; text-align: center; font-weight: 700; font-size: 36px;">
              2008
            </p>
            <div style="margin-top: 95px; left: 67px; position: absolute; width: 37px; height: 35px; background-color: #14402B; border-radius: 50%;"></div>
            <p style="position: absolute; width: 339px; font-weight: 700; line-height: 30px; right: 160px; margin-top: 60px;">
              2008년 한솔건기 설립
            </p>
            <div style="position: absolute; border: 3px solid #14402B; width: 432px; height: 0px; margin-top: 110px; right: 75px;"></div>
          </div>

          <div style="margin-top: 400px; left: 790px; width: 175px; height: 161px; position: absolute; background-color: #9AAEA7; border-radius: 50%;">
            <p style="margin-top: 30px; left: 45px; position: absolute; text-align: center; font-weight: 700; font-size: 36px;">1999</p>
            <div style="margin-top: 95px; left: 67px; position: absolute; width: 37px; height: 35px; background-color: #14402B; border-radius: 50%;"></div>
            <p style="position: absolute; width: 339px; font-weight: 700; line-height: 30px; left: 160px; margin-top: 60px;">1999년 한솔건설 설립 (전문기계타설)</p>
            <div style="position: absolute; border: 3px solid #14402B; width: 432px; height: 0px; margin-top: 110px; left: 70px;"></div>
          </div>

          
          <div style="width: 800px; right: 120px; margin-top: 650px; background-color: #9AAEA7;" class="card">
            <div style="font-weight: 800; font-size: 24px;" class="card-body">
              SH건설산업 기계타설전문
            </div>
            <p>현재의 위치에 안주하지 않고, 축적된 기술력과 우수한인력을 <br> 바탕으로 다시 한번 도약을 준비하고 있습니다.</p>
          </div>
        </div>
      

      
      
    </div>
  </div>
</div>


{% endblock %}

companies/templates/companies/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

{% endblock css %}

{% block content %}

<!-- Banner -->
<div style="margin-top: 100px;" class="card text-bg-dark">
    <img style="height: 458px; filter: brightness(50%); background-size: cover;" src="{%static 'images/60.png'%}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <div style="margin-top: 60px; margin-left: 90px;">
            <p style="animation: fadeIn; animation-duration: 2s; font-size: 54px;" 
               class="animate__animated animate__fadeIn card-title">
                끊임없는 기술혁신을 통하여 <br>
                최상의 시공품질을 유지합니다.
            </p>
        </div>
      <div style="margin-top: 20px; margin-left: 90px;">
        <p style="animation: fadeIn; animation-duration: 4s; font-size: 19px;" class="card-text">
            에스에이치건설산업 주식회사는 L형 측구, 배수공, 터널공동구, <br>
            중앙분리대, 철도터널동구, 도로경계석, 교량난간 방호벽 등 <br>
            콘크리트기계화 시공 전문업체입니다.
          </p>
      </div>
      <div style="margin-top: 20px; margin-left: 90px;">
        <p  class="card-text">
          <button type="button" class="btn btn-success">문의하기</button>
      </p>
    </div>
  </div>

  <!-- line notice 생성 구간 입니다. -->
  <section style="height: 62px; position: relative; width: 100%; display: block;" 
           class="line_notice">
    <div style="height: 62px; width: 50%; background-color: #14402B; left: 0; position: absolute; top: 0;" 
         class="line_notice_left">
    </div>
    <div style="height: 62px; width: 50%; background-color: #f6f5ef; position: absolute; right: 0; top: 0;" 
         class="line_notice_right">
    </div>
    <div style="background: none; margin-left: -400px; width: 960px; height: 62px; left: 50%; position: absolute; top: 0;" 
         class="line_notice_bg">
         <div style="width: 55%; height: 62px; float: left;" 
              class="line_notice_bg1">
          <div style="margin: 13px 0 0 20px; width: 84%; height: 36px; float: left;" 
               class="line_notice_inner">
            <dl style="width: 85%; height: 33px; float: left; position: relative;" 
                class="line_notice_inner_1">
              <dt style="background-size: 65px auto; height: 17px; left: 0; top: 10px;  position: absolute;
                           width: 200px;" 
                   class="notice_tt1">
                  <p style=" font-size: 18px;">공지사항</p>
              </dt>
              <dd style="position: absolute; left: 65px; top: 9px; width: 520px; height: 24px; text-indent: 15px; 
                         overflow: hidden;">
                <ul style="direction: 1tr; font-size: 14px; color: rgb(255, 255, 255);" 
                    class="news_result">
                  <li style=" list-style: none;">시스템 개선 및 서비스 점검 안내</li>
                </ul>
              </dd>
              <!-- NOTICE ICON -->
              <P style="height: 36px; width: 36px; float: right; position: relative;" 
                 class="line_notice_inner_r">
                <span style="background-size: 35px; height: 36px; left: 0; top: 0; width: 36px; margin-top: 7px;" 
                      class="material-symbols-rounded">
                  add_circle
                </span>
              </P>
            </dl>
          </div> 
        </div>
        <div style="width: 45%; height: 62px; z-index: 10; float: right; position: relative;" 
             class="line_notice_bgr">
            <a style="text-decoration: none; left: 10px; height: 36px; top: 13px; width: 234px; display: block; 
                      position: absolute;" 
               href="javascript:void(0);">
              <p style="margin-top: 7px; font-size: 14px;  color: #000; background-size: 100% auto; 
                        height: 17px; left: 0; top: 9px; width: 429px;"
              >
                에스에이치건설산업 주식회사 문의글 입니다.
              </p>
              <!-- NOTICE ICON -->
            </a>
            <span style="margin-top: 17px; color: #000; background-size: 35px; overflow: hidden; position: absolute;
                           height: 36px; right: 0px; top: 0px; width: 120px;" 
                    class="material-symbols-rounded">
                  expand_circle_down
            </span>
        </div>
    </div>
  </section>

<!-- 시공사례, 시공분야 -->
<!-- 시공사례 -->
<div style="background-color: #14402B; display: flex; flex-wrap: wrap; margin-right: -20px; margin-left: -20px;"  
     class="row">
  <div style="margin-top: 70px; margin-left: 270px; margin-bottom: 80px;" 
       class="col-md-4 stretch-card grid-margin">
    <div style="border-style: none; border-radius: 40px;" 
         class="card bg-gradient-danger card-img-holder text-white"
    >
      <div style=" border-radius: 40px; background: rgba(2, 36, 19, 0.658);" 
           class="card-body"
      >
        <h4 style=" margin-top: 10px; color: #fff; margin-left: 199px;" 
            class="font-weight-normal mb-3">시공사례</h4>
      </div>
    </div>
  </div>
  
  <!-- 시공분야 -->
  <div style="margin-top: 70px; margin-left: 40px; margin-bottom: 80px;" 
       class="col-md-4 stretch-card grid-margin">
       <div style="border-style: none; border-radius: 40px;" 
       class="card bg-gradient-danger card-img-holder text-white"
       >
    <div style=" border-radius: 40px; background: rgba(2, 36, 19, 0.658);" 
         class="card-body"
    >
      <h4 style=" margin-top: 10px; color: #fff; margin-left: 199px;" 
          class="font-weight-normal mb-3">시공분야</h4>
    </div>
  </div>
  </div>
</div>

<!-- The power of road construction starts here -->
<div class="text-center">
  <div class="row">
      <!-- 왼쪽 동영상 -->
    <div class="col-6">
        <video style=" width: 820px; height: 486px;" 
             autoplay controls loop muted
             src="{%static 'images/pexels-rodnae.mp4' %}">
        </video>
    </div>
      <!-- 오른쪽 글 -->
    <div style="background-color: #fff;" class="col-6">
      <p style="animation: fadeIn; animation-duration: 8s; 
         text-align: left; margin-top: 30px; margin-left: 50px; font-size: 44px; color: #000;"
         class="animate__animated animate__fadeIn"
      >
          The power of <br>
          road <br>
          construction <br>
          starts here
      </p>
      <div style="text-align: left; margin-left: 50px; margin-top: 50px;">
          <button style="color: #fff; background: rgba(10, 56, 4, 0.74);" 
                  type="button" 
                  class="btn btn-lg">
                  문의하기
          </button>
      </div>
    </div>
  </div>
</div>

<!-- 홍보 section 생성구간입니다. -->
<div style="z-index: 0; padding-top: 7px; position: relative; padding-bottom: 0 !important; box-sizing: border-box;
            background-image: url('https://images.pexels.com/photos/561201/pexels-photo-561201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');
            background-repeat: no-repeat; background-size: cover; filter: brightness(90%);" 
     class="section">
     <div style=" position: relative; text-align: center; padding-top: 100px; padding-bottom: 60px;" 
          class="toptop">
      <div style="text-align: center; box-sizing: border-box;" 
           class="header">
        <div style="z-index: 1; color: #000; margin-bottom: 15px; font-weight: 600; font-size: 2.8rem !important; line-height: 1.3px;" 
             class="head">
          SH 건설산업 기계타설전문
          <div style="padding-top: 30px; color: #000; line-height: 170%; margin: 30px 0 50px; font-size: 1.5rem;" 
               class="h5text">
            현재의 위치에 안주하지 않고, 축적된 기술력과 우수한 <br>
            인력을 바탕으로 다시 한번 도약을 준비하고 있습니다. 
          </div>
          <a style="border-radius: 30px; display: inline-block; background: rgba(10, 65, 8, 0.514); border: 1px solid #ddd; 
                    padding: 20px 70px; text-decoration: none; font-size: 18px; color: #fff;" 
             href="{% url 'companies:come' %}">오시는 길 바로가기</a>
        </div>
      </div>
     </div>
</div>
{% endblock %}

companies/templates/companies/patent.html
{% extends 'base.html' %}
{% load static %}

{% block css %}


{% endblock css %}

{% block content %}
<!-- banner 생성구간입니다. -->
<div style="margin-top: 100px;" class="card text-bg-dark">
    <img style="height: 150px; filter: brightness(50%); background-size: cover; object-fit: cover;" 
         src="{%static 'images/60.png'%}" class="card-img" alt="회사소개 윗부분 사진입니다.">
    <div class="card-img-overlay">
        <div style="margin-top: 50px; margin-left: 90px;">
            <p style="text-align: center; animation: fadeIn; animation-duration: 2s; font-size: 27px;" 
               class="animate__animated animate__fadeIn card-title">
               SH건설산업 기계타설전문 홈페이지를방문해주신 여러분 진심으로 환영합니다.
            </p>
        </div>
  </div>


  <div style="background-color: #fff;" class="content">
    <div class="container text-center">
      <div class="row">
        <div class="col-sm-4">
          <div style="margin-top: 100px;">
              <ul style="  margin-left: 80px; text-align: left;">
                  <li style=" margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:greeting' %}">
                      회사소개
                    </a>
                  </li>
                  <li style=" margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; font-weight: 700; color: #000; text-decoration: none;" href="{% url 'companies:history' %}">회사연혁</a>
                  </li>
                  <li style="font-weight: 700; margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:patent' %}">특허및인증</a>
                  </li>
                  <li style="font-weight: 700; margin-bottom: 30px;">
                    <a style="position:relative; z-index: 3; color: #000; text-decoration: none;" href="{% url 'companies:come' %}">오시는길</a>
                  </li>
              </ul>
          </div>
        </div>
  
        <!-- 세로선 -->
  
    
        <div style="margin-bottom: 300px; color: #000; margin-top: 100px; height: 500px;" class="col-sm-8">
          <div style="margin-left: 20px;">
            <div class="container text-center">
              <div class="row">
                <div class="col order-last">
                  <!-- 1 -->
                  <div class="card" style="margin-bottom: 20px; width: 18rem;">
                    <img src="{%static 'images/특허등록증.PNG'%}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">특허 등록증</h5>
                      <p class="card-text">이건 특허 등록증 입니다.</p>   
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  


{% endblock %}