SH_company_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('equipments/', include('equipments.urls')),
    path('constructions/', include('constructions.urls')),
    path('performances/', include('performances.urls')),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipments/urls.py
from django.urls import path
from . import views

app_name = 'equipments'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:equipment_pk>/', views.detail, name='detail'),
    path('<int:equipment_pk>/update/', views.update, name='update'),
    path('<int:equipment_pk>/delete/', views.delete, name='delete')
]

notices/urls.py
from django.urls import path
from . import views

app_name = 'notices'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # create라는 주소로 요청하면, create라는 VIEW 함수를 응답
    path('<int:notice_pk>/', views.detail, name='detail'),
    path('<int:notice_pk>/update/', views.update, name='update'),
    path('<int:notice_pk>/delete', views.delete, name='delete'),
    path('search/', views.search, name='search')
]

equipments/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Equipment(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    image = ProcessedImageField(upload_to='media/images/', blank=True,
                            processors=[ResizeToFill(1200, 960)],
                            format='JPEG',
                            options={'quality': 80})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class EquipImage(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    equip_img = models.ImageField('사진등록', upload_to='media/images/', blank=True, null=True) # 이미지 생략 가능

equipments/forms.py
from .models import Equipment, EquipImage
from django import forms
from django.forms import ClearableFileInput

class EquipmentForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ['image', 'title', 'content']
        labels = {'image' : '메인 이미지',
                  'title': '장비명',
                  'content': '장비 설명'
                  }
    
# 장비 디테일 페이지에 등록하는 이미지
class EquipImageForm(forms.ModelForm):
    class Meta:
        model = EquipImage
        fields = ['equip_img']
        widgets = {
            'equip_img': ClearableFileInput(attrs={'multiple': True})
        }
        labels = {
            'equip_img': '추가 이미지'
        }

equipments/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Equipment, EquipImage
from .forms import EquipmentForm, EquipImageForm

# Create your views here.
def index(request):
    equipments = Equipment.objects.order_by('-pk')
    context = {
        "equipments": equipments,
    }
    return render(request, 'equipments/index.html', context)

@login_required
def create(request):
    if request.user.is_superuser:
        if request.method == "POST":
            equipment_form = EquipmentForm(request.POST, request.FILES)
            equip_image_form = EquipImageForm(request.POST, request.FILES)
            tmp_img = request.FILES.getlist('equip_img')

            if equipment_form.is_valid() and equip_image_form.is_valid():
                equipment = equipment_form.save(commit=False)
                equipment.user = request.user

                if tmp_img:
                    for img in tmp_img:
                        img_instance = EquipImage(equipment=equipment, equip_img=img)
                        equipment.save()
                        img_instance.save()

                equipment.save()
                return redirect('equipments:index')
        else:
            equipment_form = EquipmentForm()
            equip_image_form = EquipImageForm()

        context = {
            'equipment_form': equipment_form, 
            'equip_image_form': EquipImageForm()
        }
        return render(request, 'equipments/form.html', context)
    else:
        return redirect(request, 'equipments:index')
    
def detail(request, equipment_pk):
    equipment = Equipment.objects.get(pk=equipment_pk)
    context = {
        'equipment': equipment,
    }
    return render(request, 'equipments/detail.html', context)

@login_required
def update(request, equipment_pk):
    equipment = Equipment.objects.get(pk=equipment_pk)
    equip_images = EquipImage.objects.filter(pk=equipment_pk)

    if request.user.is_superuser:
        if request.method == 'POST':
            equipment_form = EquipmentForm(request.POST, request.FILES, instance=equipment)
            # form에 equip_image 폼 추가
            equip_image_form = EquipImageForm(request.POST, request.FILES)
            tmp_img = request.FILES.getlist('equip_img')
                    
            for img in equip_images:
                if img:
                    img.delete()

            # 장비 및 장비 이미지 작성에 대한 폼이 유효하면
            if equipment_form.is_valid() and equip_image_form.is_valid():
                
                if tmp_img:
                    for img in tmp_img:
                        img_instance = EquipImage(equipment=equipment, equip_img=img)
                        equipment.save()
                        img_instance.save()

                equipment_form.save()
                return redirect("equipments:detail", equipment_pk)
        else:
            equipment_form = EquipmentForm(instance=equipment)
            if equip_images:
                equip_image_form = EquipImageForm(instance=equip_images[0])
            else:
                equip_image_form = EquipImageForm()
        context = {
            "equipment_form": equipment_form, 
            "equipment": equipment,
            "equip_image_form": equip_image_form,
        }
        return render(request, "equipments/form.html", context)
    else:
        return redirect("equipments:detail", equipment_pk)


@login_required
def delete(request, equipment_pk):
    if request.user.is_authenticated and request.user.is_superuser:
        equipment = Equipment.objects.get(pk=equipment_pk)
        equipment.delete()
        return redirect("equipments:index")

# # 검색 기능 - 요청 url 에 keyword 정보가 있는지 확인하고, 해당 키워드를 가지고 title 필드를 검색해서 키워드가 포함된 객체만 notices 에 담겨진다.
# def search(request):
#     keyword = request.GET.get("keyword", "")  # 검색어

#     if keyword:
#         equipments = Equipment.objects.filter(
#             Q(title__icontains=keyword) | Q(content__icontains=keyword) # Q는 장고 model orm으로 where 절에 or문을 추가하고 싶을 때 사용
#         ).distinct()
        
#         context = {
#             "equipments": equipments,
#             "keyword": keyword,
#         }
#         return render(request, "equipments/search.html", context)
#     else:
#         return redirect("equipments:index")

equipments/templates/equipments/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class='container' style='padding:15rem'>
    
    <div style='text-align:center'>
        <h1 class='fw-bold'>{{ equipment.title }}</h1>
        {% if equipment.image %}
            <img src='{{ equipment.image.url }}' alt='{{ equipment.image }}' style='border-radius:1rem; width:25rem; height:18rem'>
        {% endif %} 
        <h4 class='mt-3'>{{ equipment.content }}</h4>
        <div class='mt-5'>
            {% for image in equipment.equipimage_set.all %}
                <img src="{{ image.equip_img.url }}" alt="{{ image.equip_img }}" class='equip-img'
                    style="width:9rem; height:9rem; flex-shrink:0; border-radius:0.5rem">      
            {% endfor %} 
        </div>
    </div>
    
  
</div>
<div class='container'>
    {% if request.user.is_superuser == 1 %}
            <div class='mt-2 d-flex justify-content-end'>
                <p>
                <button type="button" class="btn" style="color: #fff; background: rgba(10, 56, 4, 0.74);" >
                    <a href="{% url 'equipments:update' equipment.pk %}" style='text-decoration:none; color:white' class='fw-bolder'>수정하기</a>
                </button>
                <button type="button" class="btn">
                    <a href="{% url 'equipments:delete' equipment.pk %}" style='text-decoration:none; color:#14402B' class='fw-bolder'>삭제하기</a>
                </button>
                </p>
            </div>
    {% endif %}
</div>
{% endblock %}

equipments/templates/equipments/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %} 
<div class="container" style='padding:10rem'>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form equipment_form %}
        <input type="file" name="equip_img" multiple="" accept="image/*" class="form-control"
                    id="id_equip_img">
        <div class="d-flex justify-content-end mt-3">
          <input class="btn" type="submit" value="작성완료" style="color: #fff; background: rgba(10, 56, 4, 0.74); font-weight:bold">
        </div>
    </form>
</div>
{% endblock %}

equipments/templates/equipments/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container" style="padding:10rem">
  <div style="text-align:center" >
      <h2 class="fw-bold">장비운영</h2>
  </div>
  <div class='row'>
    {% for equipment in equipments%}
    <div class='mt-3 col-sm py-3'>
      <a href="{% url 'equipments:detail' equipment.pk %}" style='text-decoration:none'>
        <div class="card" style="width: 18rem;">
          {% if equipment.image %}
          <img src="{{ equipment.image.url }}" class="card-img-top" alt="{{ equipment.image }}">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title text-center fw-bold">{{ equipment.title }}</h5>
            {% comment %} <p class="card-text">{{ equipment.content }}</p> {% endcomment %}
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  {% if request.user.is_superuser == 1 %}
  <a href="{% url 'equipments:create' %}" class='float-end'>
    <button type="subit" class="btn" style='color: #fff; background: rgba(10, 56, 4, 0.74);'>장비 등록</button>
  </a>
  {% endif %}
</div>
{% endblock %}

equipments/templates/equipments/search.html
{% extends "base.html" %}

{% block content %}
<div class='container' style='padding:10rem'>
    {% if not equipments %}
    <div class="d-flex justify-content-center">
        <h4>검색 결과가 없습니다</h4>
    </div>
    {% else %}
    <div class='row'>
        {% for equipment in equipments %}
        <div class='col'>
            <a href="{% url 'equipments:detail' equipment.pk %}" style='text-decoration:none' class='mx-2'>
                <div class="card" style="width: 18rem;">
                    {% if equipment.image %}
                    <img src="{{ equipment.image.url }}" class="card-img-top" alt="{{ equipment.image }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title text-center fw-bold">{{ equipment.title }}</h5>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}