SH_company_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('equipments/', include('equipments.urls')),
    path('constructions/', include('constructions.urls')),
    path('performances/', include('performances.urls')),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notices/urls.py
from django.urls import path
from . import views

app_name = 'notices'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # create라는 주소로 요청하면, create라는 VIEW 함수를 응답
    path('<int:notice_pk>/', views.detail, name='detail'),
    path('<int:notice_pk>/update/', views.update, name='update'),
    path('<int:notice_pk>/delete', views.delete, name='delete'),
    path('search/', views.search, name='search')
]

notices/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings


# Create your models here.
class Notice(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    image = models.ImageField(upload_to='images/',blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hits = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Photo(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

notices/forms.py
from django import forms
from .models import Notice

class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', 'content']

# ClearableFileInput으로 여러 장의 image를 입력 받을 수 있음
# class ImageForm(ModelForm):
#     class Meta:
#         model = Photo
#         fields = ['image']
#         widgets = {
#             'image': ClearableFileInput(attrs={'multiple': True})
#         }

notices/views.py
from django.shortcuts import render, redirect
from .forms import NoticeForm
from .models import Notice, Photo
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from django.core.paginator import Paginator
from django.conf import settings

# Create your views here.
def index(request):
    notices = Notice.objects.order_by('-pk')
    page = request.GET.get('page', '1')
    paginator = Paginator(notices, 5)
    paginated_notices = paginator.get_page(page)
    max_index = len(paginator.page_range)
    context = {
        'notices': notices,
        "paginated_notices": paginated_notices,
        "max_index": max_index,
    }
    return render(request, 'notices/index.html', context)

@login_required
def create(request):
    if request.user.is_superuser: # 관리자만 작성 가능
        if request.method == "POST":
            notice_form = NoticeForm(request.POST, request.FILES) # 이미지는 request.FILES로 받는다.
            if notice_form.is_valid():
                notice = notice_form.save(commit=False) #  form이 작동하고 나서 save가 작동하도록 한다.
                notice.user = request.user
                notice.save()
                for img in request.FILES.getlist('imgs'):
                    # Photo 객체를 하나 생성한다.
                    photo = Photo()
                    # 외래키로 현재 생성한 Post의 기본키를 참조한다.
                    photo.notice = notice
                    # imgs로부터 가져온 이미지 파일 하나를 저장한다.
                    photo.image = img
                    # 데이터베이스에 저장
                    photo.save()
                return redirect('notices:index')
        else:
            notice_form = NoticeForm()
        context = {
            'notice_form': notice_form,
        }
        return render(request, 'notices/form.html', context=context)
    else:
        return redirect('notices:index')

def detail(request, notice_pk):
    notice = Notice.objects.get(pk=notice_pk)
    # template에 객체 전달
    context = {
        'notice':notice,    
    }
    response = render(request, 'notices/detail.html', context)
    
    # 쿠키 이용한 조회수 기능
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()

    cookievalue = request.COOKIES.get("hitnotice", "")

    if f"{notice_pk}" not in cookievalue:
        cookievalue += f"{notice_pk}"
        response.set_cookie(
            "hitnotice", value=cookievalue, max_age=max_age, httponly=True
        )
        notice.hits += 1
        notice.save()
    return response

@login_required
def update(request, notice_pk):
    notice = Notice.objects.get(pk=notice_pk)
    # image = notice.photo_set.all()
    if request.user.is_superuser: # 관리자만 수정 가능
        if request.method == 'POST':
            notice_form = NoticeForm(request.POST, request.FILES, instance=notice)
            if notice_form.is_valid():
                notice_form.save()
                for img in request.FILES.getlist('imgs'):
                    # Photo 객체를 하나 생성한다.
                    photo = Photo()
                    # 외래키로 현재 생성한 Post의 기본키를 참조한다.
                    photo.notice = notice
                    # imgs로부터 가져온 이미지 파일 하나를 저장한다.
                    photo.image = img
                    # 데이터베이스에 저장
                    photo.save()
                    
                return redirect("notices:detail", notice_pk)
        else:
            # GET : Form을 제공
            notice_form = NoticeForm(instance=notice)
        context = {
            "notice_form": notice_form,
            "notice": notice, # notice를 context에 넘겨 줘야 수정하는 form에서 기존 작성한 것들이 보임!
        }
        return render(request, 'notices/form.html', context)
    else:
        return redirect("notices:detail", notice_pk)

@login_required
def delete(request, notice_pk):
    notice = Notice.objects.get(pk=notice_pk)
    if request.user.is_authenticated and request.user == notice.user:
        notice.delete()
        return redirect("notices:index")
    

# 검색 기능 - 요청 url 에 keyword 정보가 있는지 확인하고, 해당 키워드를 가지고 title 필드를 검색해서 키워드가 포함된 객체만 notices 에 담겨진다.
def search(request):
    keyword = request.GET.get("keyword", "")  # 검색어

    if keyword:
        notices = Notice.objects.filter(
            Q(title__icontains=keyword) | Q(content__icontains=keyword) # Q는 장고 model orm으로 where 절에 or문을 추가하고 싶을 때 사용
        ).distinct()
        
        context = {
            "notices": notices,
            "keyword": keyword,
        }
        return render(request, "notices/search.html", context)
    else:
        return redirect("notices:index")

notices/templates/notices/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container" style="padding:10rem">
    <table class = "table table-light">
            <thead class = "thead-light">
                <tr>
                    <th>제목</th>
                    <th>작성자</th>
                    <th>작성일자</th>
                    <th>조회수</th>
                </tr>
            </thead>
            <tbody class = "text-dark">
                    <th>{{ notice.title }}</th>
                    <th>{{ notice.user }}</th>
                    <th>{{ notice.created_at | date:'Y.m.d H:i' }}</th>
                    <th>{{ notice.hits }}</th>
                </tr>
            </tbody>
    </table>
    <p>{{ notice.content }}</p>
    {% for photo in notice.photo_set.all%}
    <div class='d-flex justify-content-center'>
        <img src="{{photo.image.url}}" style='width:18rem'><br>
    </div>
    {% endfor %}
    {% if request.user.is_superuser == 1 %}
        <div class='mt-2 d-flex justify-content-end'>
            <p>
            <button type="button" class="btn" style="color: #fff; background: rgba(10, 56, 4, 0.74);" >
                <a href="{% url 'notices:update' notice.pk %}" style='text-decoration:none; color:white' class='fw-bolder'>수정하기</a>
            </button>
            <button type="button" class="btn">
                <a href="{% url 'notices:delete' notice.pk %}" style='text-decoration:none; color:#14402B' class='fw-bolder'>삭제하기</a>
            </button>
            </p>
        </div>
    {% endif %}
</div>
{% endblock %}

notices/templates/notices/form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container" style="padding:10rem">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>
            <input class="input-title form-control mb-3" style="border:0px; font-size: 1.5rem;" name="title"
            placeholder="제목을 입력해주세요" value="{{ notice.title }}"  maxlength="50" required>
        </h2>
        <textarea class="form-control" placeholder="내용을 입력해주세요." name="content" required>{{ notice.content }}</textarea>
        <div class='mt-3'>
            <input type="file" name="imgs" multiple>
        </div>
        <div class="d-flex justify-content-end">
          <input class="btn fw-bold" type="submit" style="color: #fff; background: rgba(10, 56, 4, 0.74);" value="작성완료">
        </div>
    </form>
</div>
{% endblock %}

notices/templates/notices/index.html
{% extends "base.html" %}
{% load static %}
{% load notice_filter %}


{% block content %}
<div class="container" style="padding:10rem">
    <div style="text-align:center" >
        <h2 class="fw-bold">공지사항</h2>
    </div>
    <form action="{% url 'notices:search' %}" method="">
        {% csrf_token %}
        <div class="d-flex justify-content-end mb-5">
            <input class="form-control search-input mx-2" name="keyword" type="search" placeholder="검색어를 입력해주세요."
                aria-label="Search" style="width: 21rem; height: 3rem; font-weight: 400; ">
            <button type="search" class="btn fw-bold" style="background-color:#14402B; color:white">검색</button>
        </div>
    </form>
    <div class = "col-12">
        <table class = "table table-light">
            <thead class = "thead-light">
                <tr>
                    <th>번호</th>
                    <th>제목</th>
                    <th>작성자</th>
                    <th>작성일자</th>
                    <th>조회수</th>
                </tr>
            </thead>
            <tbody class = "text-dark">
                {% for notice in paginated_notices %}
                <tr onclick = "location.href = '{{notice.id}}'">
                    <th>{{ paginated_notices.paginator.count|sub:paginated_notices.start_index|sub:forloop.counter0|add:1 }}</th>
                    <th>{{ notice.title }}</th>
                    <th>{{ notice.user }}</th>
                    <th>{{ notice.created_at | date:'Y.m.d H:i'}}</th>
                    <th>{{ notice.hits }}</th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- 게시글 페이지네이션 -->
    {% if paginated_notices %}
    <ul class="pagination justify-content-center py-5">
    <!-- 첫 페이지 -->
    {% if paginated_notices.has_previous %}
    <!-- 이전페이지가 있으면 연결(첫 페이지가 아니면) -->
    <li class="page-item">
        <a class="page-link" style="color: #14402B; text-decoration: none;" tabindex="-1" href="?page=1">&#60;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">&#60;</a>
    </li>
    {% endif %}

    <!-- 페이지리스트 -->
    <!-- //페이지 범위를 하나씩 리턴 -->
    {% for page_number in paginated_notices.paginator.page_range %}
    {% if page_number >= paginated_notices.number|add:-2 and page_number <= paginated_notices.number|add:2 %} <!-- // 현재
        페이지일 때는 active -->
        {% if page_number == paginated_notices.number %}
        <li class="page-item" aria-current="page">
        <a class="page-link fw-bold" style="background-color: #14402B; color: white; text-decoration: none;"
            href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item text-color-warning">
        <a class="page-link fw-bold" style="color: #14402B; text-decoration: none;" href="?page={{ page_number }}">
            {{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if paginated_notices.has_next %}
        <li class="page-item">
        <a class="page-link fw-bold" style="color: #14402B; text-decoration: none;" href="?page={{ max_index }}">&#62;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
        <a class="page-link fw-bold" tabindex="-1" href="#">&#62;</a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
    {% if request.user.is_superuser == 1 %}
    <a href="{% url 'notices:create' %}" class='float-end'>
        <button type="subit" class="btn fw-bold" style='color: #fff; background: rgba(10, 56, 4, 0.74);color:white'>공지글 작성</button>
    </a>
    {% endif %}
</div>

{% endblock %}

notices/templates/notices/search.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container" style="padding:10rem">
    {% if not notices %}
            <div class="d-flex justify-content-center">
            <h4>검색 결과가 없습니다</h4>
            </div>
    {% else %}
            <div class = "col-12">
                <table class = "table table-light">
                    <thead class = "thead-light">
                        <tr>
                            <th>번호</th>
                            <th>제목</th>
                            <th>작성자</th>
                            <th>작성일자</th>
                        </tr>
                    </thead>
                    <tbody class = "text-dark">
                        {% for notice in notices %}
                        <tr onclick = "location.href = '/notices/{{notice.id}}'">
                            <th>{{notice.id}}</th>
                            <th>{{notice.title}}</th>
                            <th>{{notice.user}}</th>
                            <th>{{notice.created_at}}</th>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    {% endif %}
</div>
{% endblock %}