SH_company_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('equipments/', include('equipments.urls')),
    path('constructions/', include('constructions.urls')),
    path('performances/', include('performances.urls')),
    path('notices/', include('notices.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companies/urls.py
from django.urls import path
from . import views

app_name = 'companies'

urlpatterns = [
    path('', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('history/', views.history, name='history'),
    path('patent/', views.patent, name='patent'),
    path('come/', views.come, name='come'),
]

constructions/urls.py
from django.urls import path
from . import views

app_name = 'constructions'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:c_pk>/', views.detail, name='detail'),
    path('<int:c_pk>/update/', views.update, name='update'),
    path('<int:c_pk>/delete/', views.delete, name='delete'),
    path('<int:c_category_pk>/category/', views.c_category, name='c_category'),
]

equipments/urls.py
from django.urls import path
from . import views

app_name = 'equipments'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:equipment_pk>/', views.detail, name='detail'),
    path('<int:equipment_pk>/update/', views.update, name='update'),
    path('<int:equipment_pk>/delete/', views.delete, name='delete')
]

notices/urls.py
from django.urls import path
from . import views

app_name = 'notices'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # create라는 주소로 요청하면, create라는 VIEW 함수를 응답
    path('<int:notice_pk>/', views.detail, name='detail'),
    path('<int:notice_pk>/update/', views.update, name='update'),
    path('<int:notice_pk>/delete', views.delete, name='delete'),
    path('search/', views.search, name='search')
]

performances/urls.py
from django.urls import path
from . import views

app_name = 'performances'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:p_pk>/', views.detail, name='detail'),
    path('<int:p_pk>/update/', views.update, name='update'),
    path('<int:p_pk>/delete/', views.delete, name='delete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- 홈페이지 TITLE 입니다 -->
  <title>SH 건설산업(주)</title>

      <!-- 오픈그래프 카드  -->
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content="SH 건설산업" />
      <meta property="og:title" content="SH 건설산업 KOREA" />
      <meta property="og:description" content="SH 건설산업(주) 회사 홈페이지 입니다." />
      <meta property="og:image" content="{% static 'images/SH건설산업(주)_LOGO.PNG' %}" />
      <meta property="og:url" content="#" />
      <!-- 트위터 카드 -->
      <meta property="twitter:card" content="summary" />
      <meta property="twitter:site" content="SH 건설산업" />
      <meta property="twitter:title" content="SH 건설산업 KOREA" />
      <meta property="twitter:description" content="SH 건설산업(주) 회사 홈페이지 입니다." />
      <meta property="twitter:image" content="{% static 'images/SH건설산업(주)_LOGO.PNG' %}" />
      <meta property="twitter:url" content="#" />

      <!-- CSS -->
      
      {% block style %}
      <style>
        .button {
          background-color: aqua;
          transition: 0.7;
        }
      </style>
      {% endblock %}

      <!-- CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

      <!--BOOTSTRAP -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

      <!-- ANIMATE CDN -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

      <!-- GOOGLE ICON CDN -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />

      
</head>


<body style="overflow-x: hidden;">
  
  <!-- nav 생성 구간입니다. -->
  <nav style="top:0px; background-color: #fff; height: 120px;" class="fixed-top navbar navbar-expand-lg bg-body-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'companies:index' %}">
        <img style="width: 350px; margin-left: 352px;" src="{%static 'images/SH건설산업(주)_LOGO.PNG'%}" alt="">
      </a>
      <button class="navbar-toggler" 
              type="button" 
              data-bs-toggle="collapse" 
              data-bs-target="#navbarNav" 
              aria-controls="navbarNav" 
              aria-expanded="false" 
              aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li style="margin-right: 20px; text-decoration: none;" class="nav-item">
            <a style="font-size: 18px;" 
               class="nav-link active" 
               aria-current="page" 
               href="{% url 'companies:greeting'%}"
            >
              회사소개
            </a>
          </li>
          <li style="margin-right: 20px;" class="nav-item">
            <a style="font-size: 18px;" class="nav-link active" aria-current="page" href="{% url 'constructions:index' %}">
              시공분야
            </a>
          </li>
          <li style="margin-right: 20px;" class="nav-item">
            <a style="font-size: 18px;" class="nav-link active" aria-current="page" href="{% url 'performances:index' %}">
              시공실적
            </a>
          </li>
          <li style="margin-right: 20px;" class="nav-item">
            <a style="font-size: 18px;" class="nav-link active" aria-current="page" href="{% url 'equipments:index' %}">
              장비운영
            </a>
          </li>
          <li style="margin-right: 20px;" class="nav-item">
            <a style="font-size: 18px;" class="nav-link active" aria-current="page" href="{% url 'notices:index' %}">
              커뮤니티
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  
  {% block content %}{% endblock content %}
 
<!-- FOOTER 생성구간입니다.  -->
  <div style="width:100%; height: 100%; background-color: #14402B;" class="footer">
    <footer style=" margin-top: 50px; margin-bottom: 50px;" id="footer" class="footer">
      <div class="footer-content position-relative">
        <div  class="container">
          <div  class="row">
          </div>
        </div>
      </div>
      <div style="margin-top: 20px;" class="footer-legal text-center position-relative">
        <div class="container">
          <div class="copyright">
            &copy; Copyright <strong><span>COPYRIGHT ⓒ SINCE 2023 에스에이치 건설산업 주식회사</span></strong> <br>
            . All Rights Reserved
          </div>
        </div>
      </div>
    </footer>
  </div>
   




  <!--BOOTSTRAP -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

  <!-- AOS -->
</body>
</html>